version: "3"

services:
  korr:
    env_file: .env
    environment:
      - NODE_ENV=development
    volumes:
      - npm:/root/.npm
    build:
      context: .
      dockerfile: Dockerfile
    command: npm start
volumes:
  npm:
